---
steps:
  - label: FAIL
    command: exit 1
    key: main-step
  - label: ':bell: :hammer: Build a notify pipeline'
    depends_on: main_step
    command: |-
      if [ $$(buildkite-agent step get "outcome" --step "fail") == "failed" ]; then
        cat <<- YAML | buildkite-agent pipeline upload
        steps:
          - label: ":mouth: Yell at everyone"
            notify:
            - slack: '@amaury'
                message: "You have failed me."
      YAML
      else
        cat <<- YAML | buildkite-agent pipeline upload
        steps:
          - label: ":tada: WIN"
            notify:
            - slack: '@amaury'
              message: "Look, mommy! I made a devops!"
      YAML
      fi
