steps:
  - label: echo This step will fail""
    command: exit 1
    key: "main-step"  
  - wait: ~
    continue_on_failure: true
  - command: |
      if [ $$(buildkite-agent step get "outcome" --step "main-step") != "passed" ]; then
         cat <<- YAML | buildkite-agent pipeline upload 
         steps:
           - label: "Notify slack about failing step"
             command: echo "The main step has failed!"
             notify:
               - slack: "D089QF7KDR7" 
      YAML
      fi
