---
agents:
  queue: macos-local
# U088X8KCQS3
# Pipeline-level (build) notifications
notify:
  # Basic syntax - single user notification using Slack Workspace service
  - slack: U088X8KCQS3
  # Array syntax - multiple channels/users using Slack Workspace service
  - slack:
      channels: [U088X8KCQS3, builkite#test-slack-notifications]
  # Extended syntax - Multiple channels with message
  - slack:
      channels: [U088X8KCQS3, buildkite#test-slack-notifications]
      message: 'Build status update: ${BUILDKITE_BUILD_STATE}'
# Step-level notifications exmaples
steps:
  - label: Test basic syntax.
    command: echo "Running basic syntax test"
    notify:
      # Basic syntax for step notification
      - slack: '@amaury'  # Using Slack service (user handle)
  - label: Test extended syntax.
    command: echo "Testing extended syntax"
      # Extended syntax for step notifications
    notify:
      - slack:
          channels: [U088X8KCQS3, buildkite#test-slack-notifications]
          message: 'Test extended syntax: ${BUILDKITE_COMMAND_EXIT_STATUS}'
