---
notify:
  # Basic syntax - single user notification using Slack Workspace service
  - slack: U088X8KCQS3
    soft_fail:
      error_status: '*'
  # Array syntax - multiple channels/users using Slack Workspace service
  - slack:
      channels: [U088X8KCQS3, builkite#test-slack-notifications]
  # Extended syntax - Multiple channels with message
  - slack:
      channels: [U088X8KCQS3, buildkite#test-slack-notifications]
      message: 'Message attribute: 3rd step using Slack Workspace.'
# Step-level notifications exmaples
steps:
  - label: Test basic syntax.
    command: echo "1st step using Slack service."
    soft_fail:
      error_status: '*'
    notify:
      # Basic syntax for step notification
      - slack: '@amaury'  # Using Slack service (user handle)
          message: You shall not pass
  - label: Test extended syntax.
    command: echo "2nd step using Slack service."
      # Extended syntax for step notifications
    notify:
      - slack:
          channels: [U088X8KCQS3, buildkite#test-slack-notifications]
          message: 'Message attribute: 2nd step using Slack service.'
